// address type
export const GET_IDENTITY_ADDRESS = 'GET_IDENTITY_ADDRESS'
export const GET_HYDRO_ADDRESS = 'GET_HYDRO_ADDRESS'
export const ADDRESS_ERROR = 'ADDRESS_ERROR'
export const IS_HYDRO_ID_AVAILABLE = 'IS_HYDRO_ID_AVAILABLE'
export const CREATE_SIGNATURE  = 'CREATE_SIGNATURE'
export const CREATE_DEFAULT_WALLET = 'CREATE_DEFAULT_WALLET'
export const CREATE_DEFAULT_WALLET_ERROR = 'CREATE_DEFAULT_WALLET_ERROR'
export const IDENTITY_ERROR = 'IDENTITY_ERROR'

//error
export const CLEAR_ERRORS = 'CLEAR_ERRORS'