export const HYDRO_ID_KEY = 'HYDRO_ID_KEY';
export const MNEMONIC_KEY = 'MNEMONIC_KEY';
export const WALLET_ADDRESS = 'WALLET_ADDRESS';
export const HYDRO_PRIVATE_KEY = 'HYDRO_PRIVATE_KEY';
export const HYDRO_WALLET_ADDRESS = 'HYDRO_WALLET_ADDRESS';
export const PASSWORD = 'PASSWORD';
export const ENCRYPTEDKEY = 'ENCRYPTEDKEY';